Survey/Models/ManageQuestions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Survey.Models
{
    public class ManageQuestions
    {
        [Required(ErrorMessage = "Please Select Survey Name")]
        
        public IEnumerable<SelectListItem> Surveys { get; set; }
        [Display(Name = "Select Survey Name")]
        public int SurveyID { get; set; }
        [Required(ErrorMessage = "Please Select Question Group")]
        public IEnumerable<SelectListItem> Group { get; set; }
        [Display(Name = " Select Question Group")]
        public int QuestionGroupID { get; set; }

        [Required(ErrorMessage = "Please Select QuestionType")]
        public IEnumerable<SelectListItem> QuestionTypes { get; set; }
        [Display(Name = " Select Question Type")]
        public int QuestionTypeID { get; set; }
        
        [Required(ErrorMessage = "Please Enter Question")]
        [Display(Name = " Enter Question English")]
        public string QuestionE { get; set; }
        [Required(ErrorMessage = "Please Enter Question Arabic")]
        [Display(Name = " Enter Question Arabic")]
        public string QuestionA { get; set; }
        [Required(ErrorMessage = "Please Enter Answer 1")]
        [Display(Name = " Enter Answer 1 English")]
        public string Answer1E { get; set; }
        [Required(ErrorMessage = "Please Enter Answer 2")]
        [Display(Name = " Enter Answer 2 English")]
        public string Answer2E { get; set; }
        [Required(ErrorMessage = "Please Enter Answer 3")]
        [Display(Name = " Enter Answer 3 English ")]
        public string Answer3E { get; set; }
        [Required(ErrorMessage = "Please Enter Answer 4")]
        [Display(Name = " Enter Answer 4 English ")]
        public string Answer4E { get; set; }
        [Required(ErrorMessage = "Please Enter Answer 5")]
        [Display(Name = " Enter Answer 5 English")]
        public string Answer5E { get; set; }
        [Required(ErrorMessage = "Please Enter Answer 1 Arabic")]
        [Display(Name = " Enter Answer 1 Arabic ")]
        public string Answer1A { get; set; }
        [Required(ErrorMessage = "Please Enter Answer 2 Arabic")]
        [Display(Name = " Enter Answer 2 Arabic ")]
        public string Answer2A { get; set; }
        [Required(ErrorMessage = "Please Enter Answer 3 Arabic")]
        [Display(Name = " Enter Answer 3 Arabic ")]
        public string Answer3A { get; set; }
        [Required(ErrorMessage = "Please Enter Answer 4 Arabic")]
        [Display(Name = " Enter Answer 4 Arabic ")]
        public string Answer4A { get; set; }
        [Required(ErrorMessage = "Please Enter Answer 5 Arabic")]
        [Display(Name = " Enter Answer 5 Arabic ")]
        public string Answer5A { get; set; }

        public string ErrorMessage { get; set; }



    }
}

Survey/Controllers/UploadQuestionsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;



namespace Survey.Controllers
{
    public class UploadQuestionsController : Controller
    {
        readonly string connString = ConfigurationManager.ConnectionStrings["SqlConnectionString"].ConnectionString;

        
        // GET: UploadQuestions
        
        public ActionResult Index()
        {
            DataSet ds = BindSurveysDDl();
            ViewBag.Surveys = ds.Tables[0];
            List<SelectListItem> GetSurveys = new List<SelectListItem>();
            foreach (DataRow dr in ViewBag.Surveys.Rows)
            {
                GetSurveys.Add(new SelectListItem
                { Text = @dr["SurveyTitle"].ToString(), Value = @dr["SurveyID"].ToString() });
            }

            ViewBag.Surveylist = GetSurveys;

            
            
            return View();
        }

        public DataSet BindSurveysDDl()
        {
            DataSet ds = new DataSet();

            using (SqlConnection con = new SqlConnection(connString))
            {
                con.Open();
                string sql = "SELECT SurveyID,SurveyTitle FROM dbo.Surveys ";
                SqlDataAdapter da = new SqlDataAdapter(sql, con);
                da.Fill(ds);
            }

            return ds;
        }

        //public ActionResult Create(ManageQuestions ManageQuestions)
        //{
        //    try
        //    {
        //        string SurveyDDLValue = Request.Form["Surveylist"].ToString();
        //        //string QuestionGroupDDLValue = Request.Form["QuestionGrouplist"].ToString();
        //        //string QuestionTypeDDLValue = Request.Form["QuestionTypelist"].ToString();
        //        // TODO: Add insert logic here

        //        SqlConnection sqlcon = new SqlConnection(connString);
        //        var Sql = "INSERT INTO dbo.Questions " +
        //                  "(QuestionTypeId,QuestionID,QuestionEnglish,QuestionArabic,Answer1English,Answer2English,Answer3English,Answer4English,Answer5English,Answer1Arabic,Answer2Arabic,Answer3Arabic,Answer4Arabic,Answer5Arabic,SurveyID,QuestionGroupID) " +
        //                  "VALUES " +
        //                  "('" + ManageQuestions.QuestionTypeID +
        //                  "' ,(case when (Select max(QuestionID)+1 from [Questions] where SurveyID='" + SurveyDDLValue +
        //                  "') is null then 1 else (Select max(QuestionID)+1 from Questions where SurveyID='" +
        //                  SurveyDDLValue + "') end )" +
        //                  ",'" + ManageQuestions.QuestionE + "' ,N'" + ManageQuestions.QuestionA + "' ,'" +
        //                  ManageQuestions.Answer1E + "'  ,'" + ManageQuestions.Answer2E + "'  ,'" +
        //                  ManageQuestions.Answer3E + "'  " +
        //                  " ,'" + ManageQuestions.Answer4E + "','" + ManageQuestions.Answer5E + "' , N'" +
        //                  ManageQuestions.Answer1A + "'  ,N'" + ManageQuestions.Answer2A + "'  ,N'" +
        //                  ManageQuestions.Answer3A + "'  ,N'" + ManageQuestions.Answer4A + "'  ,N'" +
        //                  ManageQuestions.Answer5A + "'  ,'" + SurveyDDLValue + "','" +
        //                  ManageQuestions.QuestionGroupID + "')";
        //        var cmd = new SqlCommand(Sql, sqlcon);

        //        try
        //        {
        //            sqlcon.Open();
        //            cmd.ExecuteNonQuery();

        //        }
        //        catch (Exception ex)
        //        {

        //        }
        //        finally
        //        {
        //            sqlcon.Close();
        //            cmd.Dispose();
        //        }


        //        return RedirectToAction("Index", "ManageQuestions");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        public void UploadfromExcel(int QuestiontypeId, int QuestionId, string QuestionEnglish, string QuestionArabic,
            string Answer1English, string Answer2English, string Answer3English, string Answer4English,
            string Answer5English, string Answer1Arabic, string Answer2Arabic, string Answer3Arabic,
            string Answer4Arabic,
            string Answer5Arabic, int surveyID, int QuestionGroupID)
        {
            try
            {

               
                SqlConnection sqlcon = new SqlConnection(connString);
                var Sql = "INSERT INTO dbo.Questions " +
                          "(QuestionTypeId,QuestionID,QuestionEnglish,QuestionArabic,Answer1English,Answer2English,Answer3English,Answer4English,Answer5English,Answer1Arabic,Answer2Arabic,Answer3Arabic,Answer4Arabic,Answer5Arabic,SurveyID,QuestionGroupID) " +
                          "VALUES " +
                          "('" + QuestiontypeId + "', '"+ QuestionId+ "','" + QuestionEnglish + "' ,N'" + QuestionArabic + "' ,'" + Answer1English + "'  ,'" +
                          Answer2English + "'  ,'" + Answer3English + "'  " +
                          " ,'" + Answer4English + "','" + Answer5English + "' , N'" + Answer1Arabic + "'  ,N'" +
                          Answer2Arabic + "'  ,N'" + Answer3Arabic + "'  ,N'" + Answer4Arabic + "'  ,N'" +
                          Answer5Arabic + "'  ,'" + surveyID + "','" + QuestionGroupID + "')";
                var cmd = new SqlCommand(Sql, sqlcon);

                try
                {
                    sqlcon.Open();
                    cmd.ExecuteNonQuery();

                }
                catch (Exception ex)
                {

                }
                finally
                {
                    sqlcon.Close();
                    cmd.Dispose();
                }

            }
            catch
            {

            }
        }
        public void UpdatefromExcel(int QuestiontypeId, int QuestionId, string QuestionEnglish, string QuestionArabic,
            string Answer1English, string Answer2English, string Answer3English, string Answer4English,
            string Answer5English, string Answer1Arabic, string Answer2Arabic, string Answer3Arabic,
            string Answer4Arabic,
            string Answer5Arabic, int surveyID, int QuestionGroupID)
        {
            try
            {


                SqlConnection sqlcon = new SqlConnection(connString);
                var Sql = "Update Questions " +
                          "set  QuestionTypeId='" + QuestiontypeId + "',QuestionID='" + QuestionId + "',QuestionEnglish='" + QuestionEnglish + "'," +
                          "QuestionArabic=N'" + QuestionArabic + "',Answer1English='" + Answer1English + "',Answer2English='" + Answer2English + "'," +
                          "Answer3English='" + Answer3English + "',Answer4English='"+ Answer4English + "',Answer5English='"+ Answer5English + "'," +
                          "Answer1Arabic= N'"+ Answer1Arabic + "',Answer2Arabic=N'" + Answer2Arabic+ "N',Answer3Arabic=N'" + Answer3Arabic + "',Answer4Arabic=N'" + Answer4Arabic + "'," +
                          "Answer5Arabic=N'" + Answer5Arabic  + "',SurveyID='"+ surveyID + "',QuestionGroupID='"+ QuestionGroupID + "' where QuestionID='"+QuestionId+"' and SurveyID='"+surveyID+"' ";
                var cmd = new SqlCommand(Sql, sqlcon);

                try
                {
                    sqlcon.Open();
                    cmd.ExecuteNonQuery();

                }
                catch (Exception ex)
                {

                }
                finally
                {
                    sqlcon.Close();
                    cmd.Dispose();
                }

            }
            catch
            {

            }
        }


        //[HttpPost]
        //public ActionResult fileUpload1(HttpPostedFileBase postedFile)
        //{
        //    string SurveyDDLValue = Request.QueryString["surveyId"];
        //    string filePath;
        //    // Session["SurveyDDLValue"].ToString();
        //    if (postedFile != null)
        //    {
        //        string path = Server.MapPath("~/Uploads/");
        //        if (!Directory.Exists(path))
        //        {
        //            Directory.CreateDirectory(path);
        //        }

        //        filePath = path + Path.GetFileName(postedFile.FileName);
        //        string extension = Path.GetExtension(postedFile.FileName);
        //        postedFile.SaveAs(filePath);

        //        string conString = string.Empty;
        //        switch (extension)
        //        {
        //            case ".xls": //Excel 97-03.
        //                conString = ConfigurationManager.ConnectionStrings["Excel03ConString"].ConnectionString;
        //                break;
        //            case ".xlsx": //Excel 07 and above.
        //                conString = ConfigurationManager.ConnectionStrings["Excel07ConString"].ConnectionString;
        //                break;
        //        }

        //        DataTable dt = new DataTable();
        //        conString = string.Format(conString, filePath);

        //        using (OleDbConnection connExcel = new OleDbConnection(conString))
        //        {
        //            using (OleDbCommand cmdExcel = new OleDbCommand())
        //            {
        //                using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
        //                {
        //                    cmdExcel.Connection = connExcel;

        //                    //Get the name of First Sheet.
        //                    connExcel.Open();
        //                    DataTable dtExcelSchema;
        //                    dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);

Survey/Views/ManageQuestions/Create.cshtml
@model Survey.Models.ManageQuestions

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <br />
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <br />
        <br />
       
        <h4>Manage Questions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-4">
            @Html.LabelFor(model => model.SurveyID, htmlAttributes: new { @class = "control-label " })

            @Html.DropDownList("Surveylist", (IEnumerable
    <SelectListItem>)ViewBag.Surveylist, "--Select--", new { htmlAttributes = new { @class = "form-control" } })
            @*Html.EditorFor(model => model.SurveyID, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.SurveyID, "", new { @class = "text-danger" })
        </div>
        <br />


        <div class="col-md-4">
            @Html.LabelFor(model => model.QuestionGroupID, htmlAttributes: new { @class = "control-label " })

            @Html.DropDownList("QuestionGrouplist", (IEnumerable
   <SelectListItem>)ViewBag.QuestionGrouplist, "--Select--" , new { htmlAttributes = new { @class = "form-control" } })
            @*Html.EditorFor(model => model.QuestionGroupID, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.QuestionGroupID, "", new { @class = "text-danger" })
        </div>
        <br />


        <div class="col-md-4">
            @Html.LabelFor(model => model.QuestionTypeID, htmlAttributes: new { @class = "control-label " })

            @Html.DropDownList("QuestionTypelist", (IEnumerable
   <SelectListItem>)ViewBag.QuestionTypelist, "--Select--", new { htmlAttributes = new { @class = "form-control" } })
            @*Html.EditorFor(model => model.QuestionTypeID, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.QuestionTypeID, "", new { @class = "text-danger" })
        </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.QuestionE, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.QuestionE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionE, "", new { @class = "text-danger" })
            </div>




            <div class="col-md-4">
                @Html.LabelFor(model => model.QuestionA, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.QuestionA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionA, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer1E, htmlAttributes: new { @class = "control-label" })

                @Html.EditorFor(model => model.Answer1E, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer1E, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer2E, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer2E, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer2E, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer3E, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer3E, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer3E, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer4E, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer4E, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer4E, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer5E, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer5E, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer5E, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer1A, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer1A, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer1A, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer2A, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer2A, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer2A, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer3A, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer3A, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer3A, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer4A, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer4A, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer4A, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer5A, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer5A, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer5A, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-login float-left" />
            </div>
        </div>


    </div>

    
    }

       

Survey/Views/ManageQuestions/Edit.cshtml
@model Survey.Models.ManageQuestions

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <br />
        <br />
        <h4>ManageQuestions</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.SurveyID, htmlAttributes: new { @class = "control-label " })

                @Html.DropDownListFor(model => model.SurveyID, (IEnumerable
       <SelectListItem>)ViewBag.Surveylist, "--Select--")
                @*Html.EditorFor(model => model.SurveyID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.SurveyID, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.QuestionGroupID, htmlAttributes: new { @class = "control-label " })

                @Html.DropDownListFor(model => model.QuestionGroupID, (IEnumerable
       <SelectListItem>)ViewBag.QuestionGrouplist, "--Select--")
                @*Html.EditorFor(model => model.QuestionGroupID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.QuestionGroupID, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.QuestionTypeID, htmlAttributes: new { @class = "control-label " })

                @Html.DropDownListFor(model => model.QuestionTypeID, (IEnumerable
       <SelectListItem>)ViewBag.QuestionTypelist, "--Select--")
                @*Html.EditorFor(model => model.QuestionTypeID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.QuestionTypeID, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.QuestionE, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.QuestionE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionE, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.QuestionA, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.QuestionA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuestionA, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer1E, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer1E, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer1E, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer2E, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer2E, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer2E, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer3E, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer3E, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer3E, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer4E, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer4E, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer4E, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer5E, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer5E, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer5E, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer1A, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer1A, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer1A, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer2A, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer2A, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer2A, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer3A, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer3A, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer3A, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer4A, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer4A, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer4A, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.Answer5A, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.Answer5A, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Answer5A, "", new { @class = "text-danger" })
            </div>
            </div>

        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-login float-left" />
            </div>
        </div>
        </div>
    </div>
}

Survey/Views/ManageQuestions/Index.cshtml
@using Survey.Models
@model System.Data.DataTable
@{
    ViewBag.Title = "Index";
}
<style>

    a {
        color: white !important;
        text-decoration: none;
        background-color: transparent;
        -webkit-text-decoration-skip: objects;
    }

        a:hover {
            color: white !important;
            text-decoration: underline;
        }
</style>
<h2>Manage Questions</h2>
<br />
<br />
<div>
    <table>
        <tr class="col-md-4 ">
            <td class="btn btn-info">
            @Html.ActionLink("Add New Question", "Create", "ManageQuestions")</td>
            <td>
            </td>

            <td class="btn btn-info">
                @Html.ActionLink("Upload Questions From  Excel", "Index", "UploadQuestions")
            </td>

        </tr>
    </table>
</div>
<br />
<br />




@if (Request.QueryString["Survey"] != null)
{
    @Html.DropDownList("Surveylist", (IEnumerable<SelectListItem>)ViewBag.Surveylist, @Request.QueryString["Survey"], new { @onchange = "SelectedValue(this)" })
}
else
{
    @Html.DropDownList("Surveylist", (IEnumerable<SelectListItem>)ViewBag.Surveylist, "--Select--", new { @onchange = "SelectedValue(this)" })
}


<input type="hidden" id="txt" readonly="readonly" />
<br />
<br />
@*@Html.Hidden("SurveyName", null, new { @id = "hfSurveyName" })*@

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="table-responsive">
            <table class="table-bordered  table table-condensed">
                <thead>

                    <tr>
                        <th>Question English </th>
                        <th>Question Arabic</th>
                        <th colspan="2" style="text-align:center">Action</th>


                    </tr>
                </thead>
                @for (int i = 0; i < Model.Rows.Count; i++)
                {
            <tr>
                <td>@Model.Rows[i]["QuestionEnglish"]  </td>
                <td>@Model.Rows[i]["QuestionArabic"]  </td>
                <td >
                <button class="btn btn-warning"><a href="@Url.Action("Edit","ManageQuestions",new{@QuestionID=Model.Rows[i]["QuestionId"],@SurveyID=Model.Rows[i]["SurveyID"]})" style="color: white !important">Edit</a> </button>
                </td>
                <td >
                <button class="btn btn-danger"> @Html.ActionLink("Delete", "Delete", "ManageQuestions", new { @QuestionID = Model.Rows[i]["QuestionId"], @SurveyID = Model.Rows[i]["SurveyID"] }, new { onclick = "return confirm('Are sure wants to delete?');" })</button>
                </td>

            </tr>
                }


            </table>
        </div>
    </div>
</div>
<script>
    function SelectedValue(ddlitem) {
        var id = ddlitem.value;
        $('#txt').val = id;
        var Survey = $("#Surveylist option:selected").text();

        window.location = "/ManageQuestions/Index/?SurveyID=" + id + "&Survey=" + Survey;

    }

</script>