Quiz/Quiz/Models/ManageQuiz.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Quiz.Models
{
    public class ManageQuiz
    {
        public int QuizId { get; set; }
        [Required(ErrorMessage = "Please enter QuizName")]
        [Display(Name = "Enter Quiz Name")]
        public string QuizName { get;set;}
        [Required(ErrorMessage = "Please enter No of Levels")]
        [Display(Name = "Enter Levels")]
        public int NoOfLevels { get; set; }
        [Required(ErrorMessage = "Please enter No of Level1 Qustions")]
        [Display(Name = "Enter Level1 Questions")]
        public int NoOfQuestionsLevel1 { get; set; }
        [Required(ErrorMessage = "Please enter No of Level2 Qustions")]
        [Display(Name = "Enter Level2 Questions")]
        public int NoOfQuestionsLevel2 { get; set; }
        [Required(ErrorMessage = "Please enter No of Level3 Qustions")]
        [Display(Name = "Enter Level3 Questions")]
        public int NoOfQuestionsLevel3 { get; set; }

        
      
    }
}

Quiz/Quiz/Controllers/ManageQuizController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Quiz.Models;

namespace Quiz.Controllers
{
    public class ManageQuizController : Controller
    {
        readonly string connString = ConfigurationManager.ConnectionStrings["SqlConnectionString"].ConnectionString;
        // GET: ManageQuiz
        public ActionResult Index()
        {
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connString))
            {
                con.Open();
                string sql =
                    "SELECT  QuizId ,QuizName,NoOfLevels ,NoOfQuestionsLevel1 ,NoOfQuestionsLevel2  ,NoOfQuestionsLevel3 FROM Quiz";
                SqlDataAdapter da = new SqlDataAdapter(sql, con);
                da.Fill(dt);
            }
            return View(dt);

        }

        // GET: ManageQuiz/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ManageQuiz/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ManageQuiz/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection, ManageQuiz manageQuiz)
        {
            try
            {

                SqlConnection sqlcon = new SqlConnection(connString);
                var Sql = "INSERT INTO dbo.Quiz (QuizName ,NoOfLevels ,NoOfQuestionsLevel1 ,NoOfQuestionsLevel2 ,NoOfQuestionsLevel3) " +
                    "VALUES (@QuizName ,@NoOfLevels ,@NoOfQuestionsLevel1 ,@NoOfQuestionsLevel2 ,@NoOfQuestionsLevel3)";
                var cmd = new SqlCommand(Sql, sqlcon);
                cmd.Parameters.AddWithValue("@QuizName", manageQuiz.QuizName);
                cmd.Parameters.AddWithValue("@NoOfLevels", manageQuiz.NoOfLevels);
                cmd.Parameters.AddWithValue("@NoOfQuestionsLevel1", manageQuiz.NoOfQuestionsLevel1);
                cmd.Parameters.AddWithValue("@NoOfQuestionsLevel2", manageQuiz.NoOfQuestionsLevel2);
                cmd.Parameters.AddWithValue("@NoOfQuestionsLevel3", manageQuiz.NoOfQuestionsLevel3);

                try
                {
                    sqlcon.Open();
                    cmd.ExecuteNonQuery();

                }
                catch (Exception ex)
                {

                }
                finally
                {
                    sqlcon.Close();
                    cmd.Dispose();
                }


                return RedirectToAction("Index", "ManageQuiz");
            }
            catch
            {
                return View();
            }
        }

        // GET: ManageQuiz/Edit/5
        public ActionResult Edit(int id)
        {
            ManageQuiz manageQuiz = new ManageQuiz();
            DataTable datatable = new DataTable();
            using (SqlConnection con = new SqlConnection(connString))
            {
                con.Open();
                string sql =
                    "SELECT * from Quiz where QuizID='" + id + "' ";
                SqlDataAdapter da = new SqlDataAdapter(sql, con);
                da.Fill(datatable);
            }

            if (datatable.Rows.Count == 1)
            {
                manageQuiz.QuizName = datatable.Rows[0]["QuizName"].ToString();
                manageQuiz.NoOfLevels = Convert.ToInt32(datatable.Rows[0]["NoOfLevels"]);
                manageQuiz.NoOfQuestionsLevel1 = Convert.ToInt32(datatable.Rows[0]["NoOfQuestionsLevel1"]);
                manageQuiz.NoOfQuestionsLevel2 = Convert.ToInt32(datatable.Rows[0]["NoOfQuestionsLevel2"]);
                manageQuiz.NoOfQuestionsLevel3 = Convert.ToInt32(datatable.Rows[0]["NoOfQuestionsLevel3"]);

                return View(manageQuiz);

            }

            return RedirectToAction("Index", "ManageQuiz");
        }
    

        // POST: ManageQuiz/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection,ManageQuiz manageQuiz)
        {
            try
            {

                using (SqlConnection con = new SqlConnection(connString))
                {

                    string sql = "UPDATE dbo.Quiz    " +
                        "SET QuizName = @QuizName" +
                        ",NoOfLevels = @NoOfLevels" +
                        ",NoOfQuestionsLevel1 = @NoOfQuestionsLevel1" +
                        ",NoOfQuestionsLevel2 = @NoOfQuestionsLevel2," +
                        "NoOfQuestionsLevel3 = @NoOfQuestionsLevel3 " +
                        "WHERE QuizId='"+ id +"'";
                    SqlCommand cmd = new SqlCommand(sql, con);
                    cmd.Parameters.AddWithValue("@QuizName", manageQuiz.QuizName);
                    cmd.Parameters.AddWithValue("@NoOfLevels", manageQuiz.NoOfLevels);
                    cmd.Parameters.AddWithValue("@NoOfQuestionsLevel1", manageQuiz.NoOfQuestionsLevel1);
                    cmd.Parameters.AddWithValue("@NoOfQuestionsLevel2", manageQuiz.NoOfQuestionsLevel2);
                    cmd.Parameters.AddWithValue("@NoOfQuestionsLevel3", manageQuiz.NoOfQuestionsLevel3);


                    try
                    {
                        con.Open();
                        cmd.ExecuteNonQuery();
                    }
                    finally
                    {
                        con.Close();
                        cmd.Dispose();
                    }
                }

                return RedirectToAction("Index", "ManageQuiz");
            }
            catch
            {
                return View();
            }
        }

        // GET: ManageQuiz/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add insert logic here

                SqlConnection sqlcon = new SqlConnection(connString);
                var Sql = "Delete from [dbo].[Quiz] where QuizId=@QuizId";
                var cmd = new SqlCommand(Sql, sqlcon);
                cmd.Parameters.AddWithValue("@QuizId", id);
                try
                {
                    sqlcon.Open();
                    cmd.ExecuteNonQuery();

                }
                finally
                {
                    sqlcon.Close();
                    cmd.Dispose();
                }



            }
            catch
            {

            }
            return RedirectToAction("Index", "ManageQuiz");
        }

        // POST: ManageQuiz/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Quiz/Quiz/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Quiz.Models;

namespace Quiz.Controllers
{
    public class QuizController : Controller
    {
        readonly string connString = ConfigurationManager.ConnectionStrings["SqlConnectionString"].ConnectionString;
        // GET: Quiz
        public ActionResult Index(int id)
        {
            
            Session["QuizID"] = id;

           
            //if (Request.QueryString["teamid"] != null)
            //{

            //    if (Request.QueryString["answer"] != null)
            //    {
            //        dt = GetQuestionLevel1();
            //        Session["QuestionId"] = dt.Rows[0]["QuestionId"].ToString();
            //        Session["Points"] = dt.Rows[0]["Points"].ToString();
            //    }
            //}

            if (Request.QueryString["teamid"] != null)
            {
                string teamid = Request.QueryString["teamid"].ToString();
                if (Request.QueryString["answer"] != null)
                {
                    string answer = Request.QueryString["answer"].ToString();
                    int points = getpoints(Convert.ToInt32(Session["QuestionId"]), answer);
                    SaveResults(id, teamid, Convert.ToInt32(Session["QuestionId"]), answer, points);
                }

            }
            DataSet dtPoints = new DataSet();
            dtPoints = getTeamPoints(Convert.ToInt32(Session["QuizID"]));
            ViewData["team1"] = 0;
            ViewData["team2"] = 0;
            ViewData["team3"] = 0;
            ViewData["team4"] = 0;
            if (dtPoints.Tables[0].Rows.Count>0)
            {
                ViewData["team1"] = dtPoints.Tables[0].Rows[0]["Points"];
            }
            if (dtPoints.Tables[1].Rows.Count > 0)
            {
                ViewData["team2"] = dtPoints.Tables[1].Rows[0]["Points"];
            }
            if (dtPoints.Tables[2].Rows.Count > 0)
            {
                ViewData["team3"] = dtPoints.Tables[2].Rows[0]["Points"];
            }
            if (dtPoints.Tables[3].Rows.Count > 0)
            {
                ViewData["team4"] = dtPoints.Tables[3].Rows[0]["Points"];
            }
            DataTable dt = new DataTable();
            dt = GetQuestionLevel1();
            Session["QuestionId"] = dt.Rows[0]["QuestionId"].ToString();
            Session["Points"] = dt.Rows[0]["Points"].ToString();
             
            RadioButtonLiatModel _radiobuttonliatmodel = new RadioButtonLiatModel();
            _radiobuttonliatmodel.RadioButtonListData = new List<RadioButtonData>();
            _radiobuttonliatmodel.Question = dt.Rows[0]["Question"].ToString();
            _radiobuttonliatmodel.RadioButtonListData.Add(new RadioButtonData { Id = "inlineRadio1", Value = dt.Rows[0]["Option1"].ToString(), correctAnswer= dt.Rows[0]["RightAnswer"].ToString() });
            _radiobuttonliatmodel.RadioButtonListData.Add(new RadioButtonData { Id = "inlineRadio1", Value = dt.Rows[0]["Option2"].ToString(), correctAnswer = dt.Rows[0]["RightAnswer"].ToString() });
            _radiobuttonliatmodel.RadioButtonListData.Add(new RadioButtonData { Id = "inlineRadio1", Value = dt.Rows[0]["Option3"].ToString(), correctAnswer = dt.Rows[0]["RightAnswer"].ToString() });
            _radiobuttonliatmodel.RadioButtonListData.Add(new RadioButtonData { Id = "inlineRadio1", Value = dt.Rows[0]["Option4"].ToString(), correctAnswer = dt.Rows[0]["RightAnswer"].ToString() });

            return View(_radiobuttonliatmodel);
        }
        [HttpPost]
        public ActionResult Index(FormCollection formCollection,int id)
        {

            
            return View("Index");
        }
        public DataTable GetQuestionLevel1()
        {
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connString))
            {

                string sql =
                    "SELECT  QuestionId,Question,ltrim(rtrim(Option1)) Option1 ,ltrim(rtrim(Option2))Option2,ltrim(rtrim(Option3))Option3,ltrim(rtrim(Option4))Option4," +
                    "Points,RightAnswer ,QuestionLevel ,GoldenQuestion,QuestionArabic,Option1Arabic ,Option2Arabic ,Option3Arabic,Option4Arabic ,RightAnswerArabic FROM Questions " +
                    " where  QuestionLevel=1 and GoldenQuestion='No' and QuestionId not in (SELECT [QuestionId] FROM [TempAnswer]) ORDER BY NEWID()";
                SqlDataAdapter da = new SqlDataAdapter(sql, con);

                con.Open();
                try
                {
                    da.Fill(dt);

                }
                finally
                {
                    con.Close();
                    da.Dispose();
                }

            }
            return dt;
        }
        public int getpoints(int QuestionId, string RightAnswer)
        {
            int points = 0;
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connString))
            {

                string sql =
                    "SELECT    Points  FROM Quiz.dbo.Questions where QuestionId ='"+ QuestionId+"' and RightAnswer='"+RightAnswer+"'";
                SqlDataAdapter da = new SqlDataAdapter(sql, con);

                con.Open();
                try
                {
                    da.Fill(dt);
                    if(dt.Rows.Count>0)
                    {
                        points = Convert.ToInt32(dt.Rows[0]["Points"]);
                    }

                }
                finally
                {
                    con.Close();
                    da.Dispose();
                }

            }
           
            return points;
        }
        public DataSet getTeamPoints(int QuizId)
        {
            DataSet ds = new DataSet();
            using (SqlConnection con = new SqlConnection(connString))
            {
                string sql =
                    "SELECT Sum(Points) Points,TeamId FROM Quiz.dbo.Answers where  QuizId = '"+QuizId+ "' and TeamId = 'Team1'   group by TeamId " +
                    "SELECT  Sum(Points) Points,TeamId FROM Quiz.dbo.Answers where  QuizId = '" + QuizId + "' and TeamId = 'Team2'   group by TeamId " +
                    "SELECT  Sum(Points) Points,TeamId FROM Quiz.dbo.Answers where  QuizId = '" + QuizId + "' and TeamId = 'Team3'   group by TeamId " +
                    "SELECT Sum(Points) Points,TeamId FROM Quiz.dbo.Answers where  QuizId = '" + QuizId + "' and TeamId = 'Team4'   group by TeamId ";
                SqlDataAdapter da = new SqlDataAdapter(sql, con);

                con.Open();
                try
                {
                    da.Fill(ds);
                    

                }
                finally
                {
                    con.Close();
                    da.Dispose();
                }

            }

            return ds;
        }
        public DataTable GetQuestionLevel2()
        {
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connString))
            {

                string sql =
                    "SELECT top 1 * FROM [Quiz].[dbo].[Questions]" +
                    " where  QuestionLevel=2 and GoldenQuestion='No'  " +
                    "and QuestionId " +
                    "not in (SELECT [QuestionId] FROM [TempAnswer]) " +
                    "ORDER BY NEWID()";
                SqlDataAdapter da = new SqlDataAdapter(sql, con);
                con.Open();
                try
                {
                    da.Fill(dt);

                }
                finally
                {
                    con.Close();
                    da.Dispose();
                }

            }
            return dt;
        }
        public DataTable GetGoldenQuestion()
        {
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connString))
            {

                string sql =
                    "SELECT top 1 * FROM [Quiz].[dbo].[Questions] " +
                    "where   GoldenQuestion='Yes'  and QuestionId " +
                    "not in (SELECT [QuestionId] FROM [TempAnswer]) " +
                    "ORDER BY NEWID()";
                SqlDataAdapter da = new SqlDataAdapter(sql, con);
                con.Open();
                try
                {
                    da.Fill(dt);

                }
                finally
                {
                    con.Close();
                    da.Dispose();
                }
            }
            return dt;
        }
        public DataTable GetLevels()
        {
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connString))
            {

                string sql =
                    "SELECT [NoOfLevels] ,[NoOfQuestionsLevel1],[NoOfQuestionsLevel2],[NoOfQuestionsLevel3] FROM [Quiz].[dbo].[Quiz] where Quizid='1'";
                SqlDataAdapter da = new SqlDataAdapter(sql, con);
                con.Open();
                try
                {
                    da.Fill(dt);

                }
                finally
                {
                    con.Close();
                    da.Dispose();
                }
            }
            return dt;
        }
        [HttpPost]
        public void Test()
        {

        }
        [HttpPost]
        public void SaveResults(int QuizId, string TeamId, int QuestionId,string Answer,int Points)
        {
            try
            {
                // TODO: Add insert logic here

                SqlConnection sqlcon = new SqlConnection(connString);
                var Sql = "INSERT INTO dbo.Answers (QuizId,TeamId,QuestionId,Answer,Points) " +
                    "VALUES  " +

Quiz/Quiz/Views/ManageQuiz/Create.cshtml
@model Quiz.Models.ManageQuiz

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <br />
        <br />

        <h4>Manage Quiz</h4>
        <hr />
        <div class="row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="col-md-4">
                @Html.LabelFor(model => model.QuizName, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.QuizName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuizName, "", new { @class = "text-danger" })
            </div>
            <br />


            <div class="col-md-4">
                @Html.LabelFor(model => model.NoOfLevels, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.NoOfLevels, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfLevels, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.NoOfQuestionsLevel1, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.NoOfQuestionsLevel1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfQuestionsLevel1, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">

            <div class="col-md-4">
                @Html.LabelFor(model => model.NoOfQuestionsLevel2, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.NoOfQuestionsLevel2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfQuestionsLevel2, "", new { @class = "text-danger" })
            </div>




            <div class="col-md-4">
                @Html.LabelFor(model => model.NoOfQuestionsLevel3, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.NoOfQuestionsLevel3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfQuestionsLevel3, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-login float-left" />
            </div>
        </div>
    </div>
    </div>
        }
                    

                   

Quiz/Quiz/Views/ManageQuiz/Edit.cshtml
@model Quiz.Models.ManageQuiz

@{
    ViewBag.Title = "Edit";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <br />
        <br />

        <h4>Manage Quiz</h4>
        <hr />
        <div class="row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="col-md-4">
                @Html.LabelFor(model => model.QuizName, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.QuizName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuizName, "", new { @class = "text-danger" })
            </div>
            <br />


            <div class="col-md-4">
                @Html.LabelFor(model => model.NoOfLevels, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.NoOfLevels, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfLevels, "", new { @class = "text-danger" })
            </div>


            <div class="col-md-4">
                @Html.LabelFor(model => model.NoOfQuestionsLevel1, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.NoOfQuestionsLevel1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfQuestionsLevel1, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">

            <div class="col-md-4">
                @Html.LabelFor(model => model.NoOfQuestionsLevel2, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.NoOfQuestionsLevel2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfQuestionsLevel2, "", new { @class = "text-danger" })
            </div>




            <div class="col-md-4">
                @Html.LabelFor(model => model.NoOfQuestionsLevel3, htmlAttributes: new { @class = "control-label " })

                @Html.EditorFor(model => model.NoOfQuestionsLevel3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfQuestionsLevel3, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-login float-left" />
            </div>
        </div>
    </div>
</div>
}


                 

Quiz/Quiz/Views/ManageQuiz/Index.cshtml
@model System.Data.DataTable
    @{
    ViewBag.Title = "Index";
}

<style>

    a {
        color: white !important;
        text-decoration: none;
        background-color: transparent;
        -webkit-text-decoration-skip: objects;
    }

        a:hover {
            color: white !important;
            text-decoration: underline;
        }
</style>
<style>
    .delete-section {
        display: inline;
    }
</style>
<h4>Manage Quiz</h4>
<br />
<br />
<div>
    <table>
        <tr class="col-md-4 ">


            @if (Session["Role"] != null)
            {
                switch (Session["Role"])
                {
                    case "Admin":
            <td class="btn btn-info">
                @Html.ActionLink("Add New Quiz", "Create", "ManageQuiz")
            </td>
                            break;

                            }
                            }
                        
                    </tr>
    </table>
</div>
<br />
<br />

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="table-responsive">
            <table class="table-bordered  table table-condensed">
                <thead>
                    <tr>
                        <th>Quiz Name </th>
                        <th>Levels </th>

                        <th colspan="2" style="text-align:center">Action</th>


                    </tr>
                </thead>
                @if (Session["Role"] != null)
                {
                    switch (Session["Role"])
                    {
                        case "Admin":

                            for (int i = 0; i < Model.Rows.Count; i++)
                            {
                                <tr>
                                    <td>@Model.Rows[i]["QuizName"]  </td>
                                    <td>@Model.Rows[i]["NoOfLevels"]  </td>

                                    <td>
                                        <button class="btn btn-warning"><a href="@Url.Action("Edit", "ManageQuiz", new { @id = Model.Rows[i]["QuizID"] })" style="color: white !important">Edit</a></button>
                                    </td>

                                    <td>
                                        <button class="btn btn-danger"> @Html.ActionLink("Delete", "Delete", "ManageQuiz", new { @id = Model.Rows[i]["QuizID"] }, new { onclick = "return confirm('Are sure wants to delete?');" })</button>
                                    </td>

                                </tr>
                            }
                            break;
                        case "Coordinator":
                            for (int i = 0; i < Model.Rows.Count; i++)
                            {
                                <tr>
                                    <td>@Model.Rows[i]["QuizName"]  </td>
                                    <td>@Model.Rows[i]["NoOfLevels"]  </td>

                                    <td>
                                        <button class="btn btn-warning"><a href="@Url.Action("Index", "Quiz", new { @id = Model.Rows[i]["QuizID"] })" style="color: white !important">Conduct</a></button>
                                    </td>

                                    

                                </tr>
                            }
                            break;

                    }
                }


            </table>
        </div>
    </div>
</div>